version: '3.3'

services:
  db:
    image: mysql:8.0.30
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'keepstrong'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
